language: python
python:
- '3.6'
install:
 - sudo apt-get update
 - pip install -r requirements.txt
 - cd $HOME
 - git clone https://github.com/imperial-genomics-facility/data-management-python.git
 - cd -
 - cd $HOME/data-management-python
 - git checkout metadata_201908
 - cd -
 - export PYTHONPATH="$HOME/data-management-python:$PYTHONPATH"
 - echo $PYTHONPATH
script:
 - coverage run --source=app setup.py test
after_success:
- coverage combine
- coveralls
notifications:
  slack:
    secure: c0YtfTFtGgK2deesuMBBdEURwlXvJwc1UC9JKjMKQ+5mUHwEicIO0T4YlsI7KzHFBue01bE6zn9p7Az9Bp5VFzQUAjCMzJ25ScBJan/RWEuYA/A3uz5WOcFA0Th0bZu6Zu0bGkk9goyYvUNpzA50Dav7bqvrn1k6HOEBaj3GhA949T3WG1tSWCYktphqgyMV1MW0o5j5KFGqK08034Ex2t8l+Om25RANAJwf+6dVLKpJJvrlqbk7O0PgJXiCZmcCyysWHpY9+ZLk5zFAuADBThKt6PycYRX8sDOgTqt29DhpCKXOMfUPwQVN9yaHcQCLFxWJEcoxdNNy65jFGmPg9oMvzA1gHq1bVgBqZ/bN35WUShqL4eBELL7C5rhtednh46bBNeFTz37CtdZRvi21EXK7kuKT/+5bqlt+uUWYt3QoPGykgD42pg9c9XaGnXCI6rZ/F0ACLrxMR8DEKcqxFKIhI+aUieBUruyHmHhRUSkUX4iPtY/tCQriE69/McaToRae0d0p8GSF1UXv9jihzQJJ8DS5S9mlSY5NzMvteDi5yptBeYmKdSIy1/MG24j4MBevzfXO8M+JiIA40rCx/yaoKt9haAvDU9gzOCGSdNdNFsNXsLxY3mPMC5QFcNXdshq6Gv9HZhoRRnZV9l0pIx2mclvvadbszFAOpqKYajE=
