language: python
python:
- '3.6'
install:
 - sudo apt-get update
 - pip install -r requirements.txt
 - cd $HOME
 - git clone https://github.com/imperial-genomics-facility/data-management-python.git
 - cd -
 - cd $HOME/data-management-python
 - git checkout metadata_201908
 - cd -
 - export PYTHONPATH="$HOME/data-management-python:$PYTHONPATH"
 - echo $PYTHONPATH
script:
 - coverage run --source=app setup.py test