language: python
python:
- '3.6'
install:
- sudo apt-get update
- pip install -r requirements.txt
- cd $HOME
- git clone https://github.com/imperial-genomics-facility/data-management-python.git
- cd -
- cd $HOME/data-management-python
- git checkout metadata_201908
- cd -
- export PYTHONPATH="$HOME/data-management-python:$PYTHONPATH"
- echo $PYTHONPATH
script:
- coverage run --source=app setup.py test
after_success:
- coverage combine
- coveralls
notifications:
  slack:
    secure: oJq7Ckf+XEkAH3pZn1SYrEKQmskHpQWT/npx4dkJS3gAgMD0rHs2dgDrvmbpeMBfcCKMZbxR7mN3xHzBjhcRapBDts+ChW1GMr1agCi8zXA5mMh6+7FR2kvj8oLXYmK91mEINxsKDKz64Xa+7B2UnARR4IJ0HreVfQaTLWi6QS1GQHzC62RMKHeDMCK8XMN4b0EHAsBR01DL6nOUn2xOn4wu6p8PfwWBXfQk+tmPhZZNwspP3MjLPOYQZzbiuBzTzShZztu9i/gLTq6m2NDWj2c3IBJHlI9Fc3+01JrwshYH91x7xV8dS2RRDuHmp2F3KYHMxlmPBd4DVDuiwOSKYsDsFVFca89n+O0HuU232Ti++MahUuB0olHZLtWg1hQlduqOlslz7gk7P1nXtHkUzygbQBbo1nD+TG8fpFt829+yYEB7j/RnYLamuoqsq41JE75zD3dUs3tcjc+bkujLEX0O8oVAAfpGY19F5Yhr4hDGVXwC4jgbKC8FXx7wDxXDhlLldS61nMGgjlOUT3L/hrhs2G6GSTklFJgjVU9HTMN4IFzRkSMiRoGXRvjhQcQpExQosQrTmCddtQHMVnZkym3+dMomRT7tHH5ouY0TWYp2xOagYDmGkj8yOKZ8vT75Z19+QXMC76gSxnBFeZzsmLI1X/ut8xLV7w3Bsef8hYA=
