"""initial test commit

Revision ID: 5908ebbfecc4
Revises: 
Create Date: 2019-09-12 11:02:48.053143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5908ebbfecc4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assay_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assay_name', sa.String(length=30), nullable=True),
    sa.Column('read_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assay_name')
    )
    op.create_table('platform',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('m_reads', sa.Integer(), nullable=True),
    sa.Column('m_bases', sa.Integer(), nullable=True),
    sa.Column('m_clusters', sa.Integer(), nullable=True),
    sa.Column('m_output', sa.Integer(), nullable=True),
    sa.Column('clusters', sa.Integer(), nullable=True),
    sa.Column('lanes', sa.Integer(), nullable=True),
    sa.Column('max_samples', sa.Integer(), nullable=True),
    sa.Column('is_pe', sa.Integer(), nullable=True),
    sa.Column('read_length', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('platform')
    op.drop_table('assay_type')
    # ### end Alembic commands ###
