"""added sc column for assay table

Revision ID: ad5d53967e4a
Revises: 5908ebbfecc4
Create Date: 2019-10-01 11:24:43.060445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad5d53967e4a'
down_revision = '5908ebbfecc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assay_type', sa.Column('is_sc', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assay_type', 'is_sc')
    # ### end Alembic commands ###
